### ISSUE TITLE
Use audited noble-hashes instead of js-sha3

### ISSUE THREAD

**Issue by paulmillr** [multiformats/js-sha3#48]
js-sha3 has a couple bugs. https://github.com/paulmillr/noble-hashes is an audited alternative developed with grant from Ethereum Foundation. It could be better to switch to it.

**Comment by BigLep** [comment]
@paulmillr : are there user problems that you're aware of that will be fixed with the change over to nobile-hashes?

**Comment by paulmillr** [comment]
@BigLep yes

**Comment by BigLep** [comment]
@paulmillr : can you elaborate?  There's not much maintainer bandwidth for this repo and I'm trying to get a sense of how valuable this dependency change is.

**Comment by paulmillr** [comment]
The new dependency is audited. The old one has not been audited.

**Comment by BigLep** [comment]
@paulmillr : with minimal maintainer bandwidth and without any user complaints here, maintainers aren't going to take this on.  If you'd like to contribute a PR, maintainers will look at it.

**Comment by ukstv** [comment]
@BigLep  > without any user complaints here

I do complain :) No, seriously, we as representatives of the ecosystem better move to crypto dependencies being audited. Bonus point: the maintainer of noble-crypto is alive and cares about his stuff.

**Comment by rvagg** [comment]
@ukstv if you see merit in a switch then would you (or someone else reading this) mind submitting a PR for a change?
